name: Format and Lint Code
on:
  push:
permissions:
  contents: write
jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Black
        uses: psf/black@stable
        with:
          options: "-S"
      - name: Commit changes
        run: |
          git config --global user.name 'GitHubBot'
          git config --global user.email 'GitHubBot@users.noreply.github.com'
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Format code with Black."
            git push
          fi
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Flake8
        run: flake8 .
